<?php

namespace Database\Seeders;

use App\Models\AppModule;
use Illuminate\Database\Seeder;

class AppModuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $appId = config('app.admin_app_id');
        AppModule::insert([
            [
                'id' => 100,
                'app_id' => $appId,
                'name' => 'user_management',
                'native_name' => 'User Management',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 150,
                'app_id' => $appId,
                'name' => 'driver_management',
                'native_name' => 'Driver Management',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 200,
                'app_id' => $appId,
                'name' => 'merchant_management',
                'native_name' => 'Merchant Management',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 251,
                'app_id' => $appId,
                'name' => 'booking_center',
                'native_name' => 'Booking Center',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 252,
                'app_id' => $appId,
                'name' => 'package_trails',
                'native_name' => 'Package Trails',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 253,
                'app_id' => $appId,
                'name' => 'Fleet Management',
                'native_name' => 'Fleet Management',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 254,
                'app_id' => $appId,
                'name' => 'completed_deliveries',
                'native_name' => 'Completed Deliveries',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 255,
                'app_id' => $appId,
                'name' => 'Driver Transaction',
                'native_name' => 'Driver Transaction',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 256,
                'app_id' => $appId,
                'name' => 'Driver Balance',
                'native_name' => 'Driver Balance',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 257,
                'app_id' => $appId,
                'name' => 'driver_commission',
                'native_name' => 'Driver Commission',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 258,
                'app_id' => $appId,
                'name' => 'merchant_transaction',
                'native_name' => 'Merchant Transaction',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 259,
                'app_id' => $appId,
                'name' => 'merchant_balance',
                'native_name' => 'Merchant Balance',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 260,
                'app_id' => $appId,
                'name' => 'driver_management',
                'native_name' => 'Driver Management',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 261,
                'app_id' => $appId,
                'name' => 'merchant_management',
                'native_name' => 'Merchant Management',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 262,
                'app_id' => $appId,
                'name' => 'pickup_list',
                'native_name' => 'Pickup List',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 263,
                'app_id' => $appId,
                'name' => 'daily_packages_list',
                'native_name' => 'Daily Packages List',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 264,
                'app_id' => $appId,
                'name' => 'daily_package_summary',
                'native_name' => 'Daily Package Summary',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 265,
                'app_id' => $appId,
                'name' => 'settle_statement',
                'native_name' => 'Settle Statement',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 266,
                'app_id' => $appId,
                'name' => 'operations_summary',
                'native_name' => 'Operations Summary',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 267,
                'app_id' => $appId,
                'name' => 'review_and_feedback',
                'native_name' => 'Review and Feedback',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 268,
                'app_id' => $appId,
                'name' => 'merchant_list',
                'native_name' => 'Merchant List',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 269,
                'app_id' => $appId,
                'name' => 'merchant_summary',
                'native_name' => 'Merchant Summary',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 270,
                'app_id' => $appId,
                'name' => 'merchant_payment',
                'native_name' => 'Merchant Payment',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 271,
                'app_id' => $appId,
                'name' => 'merchant_list_(owe_fees)',
                'native_name' => 'Merchant List (Owe Fees)',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 272,
                'app_id' => $appId,
                'name' => 'driver_list',
                'native_name' => 'Driver List',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 273,
                'app_id' => $appId,
                'name' => 'driver_delivery_summary',
                'native_name' => 'Driver Delivery Summary',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 274,
                'app_id' => $appId,
                'name' => 'payment_by_driver',
                'native_name' => 'Payment By Driver',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 275,
                'app_id' => $appId,
                'name' => 'detail_package_by_driver',
                'native_name' => 'Detail Package by Driver',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 276,
                'app_id' => $appId,
                'name' => 'driver_commission_payment',
                'native_name' => 'Driver Commission Payment',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 277,
                'app_id' => $appId,
                'name' => 'company_profile',
                'native_name' => 'Company Profile',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 278,
                'app_id' => $appId,
                'name' => 'brand_images',
                'native_name' => 'Brand Images',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 279,
                'app_id' => $appId,
                'name' => 'promotion',
                'native_name' => 'Promotion',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 280,
                'app_id' => $appId,
                'name' => 'social_media',
                'native_name' => 'Social Media',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 281,
                'app_id' => $appId,
                'name' => 'privacy_statement',
                'native_name' => 'Privacy Statement',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 282,
                'app_id' => $appId,
                'name' => 'terms_and_conditions',
                'native_name' => 'Terms And Conditions',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 283,
                'app_id' => $appId,
                'name' => 'exchange_rate',
                'native_name' => 'Exchange Rate',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 284,
                'app_id' => $appId,
                'name' => 'product_categories',
                'native_name' => 'Product Categories',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 285,
                'app_id' => $appId,
                'name' => 'remarks',
                'native_name' => 'Remarks',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 286,
                'app_id' => $appId,
                'name' => 'countries_and_cities',
                'native_name' => 'Countries and Cities',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 287,
                'app_id' => $appId,
                'name' => 'delivery_zone',
                'native_name' => 'Delivery Zone',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 288,
                'app_id' => $appId,
                'name' => 'zone_prices',
                'native_name' => 'Zone Prices',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 289,
                'app_id' => $appId,
                'name' => 'bank',
                'native_name' => 'Bank',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 290,
                'app_id' => $appId,
                'name' => 'user_management',
                'native_name' => 'User Management',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
        ]);
    }
    public function rollback()
    {
        // Rollback logic, e.g., delete the seeded data
        AppModule::query()->delete();
    }
}
