<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
         Permission::insert([
            //** Booking Center */
            [
                'id' => 200,
                'module_id' => 251,
                'name' => 'Quick Order',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 201,
                'module_id' => 251,
                'name' => 'Assign Driver',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 202,
                'module_id' => 251,
                'name' => 'Change Status',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 203,
                'module_id' => 251,
                'name' => 'Change Driver',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 204,
                'module_id' => 251,
                'name' => 'Delete Order',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 205,
                'module_id' => 251,
                'name' => 'Add Package',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 206,
                'module_id' => 251,
                'name' => 'Edit Package',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 207,
                'module_id' => 251,
                'name' => 'Delete Package',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 208,
                'module_id' => 251,
                'name' => 'Print Daily Package',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],

            //** Package Trails */
            [
                'id' => 209,
                'module_id' => 252,
                'name' => 'Assign Driver',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 210,
                'module_id' => 252,
                'name' => 'Return to store',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 211,
                'module_id' => 252,
                'name' => 'Change Merchant',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 212,
                'module_id' => 252,
                'name' => 'Delete Package',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 213,
                'module_id' => 252,
                'name' => 'Print Package',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 214,
                'module_id' => 252,
                'name' => 'Edit Package',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],

            //** Fleete */
            [
                'id' => 215,
                'module_id' => 253,
                'name' => 'New Trip',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 216,
                'module_id' => 253,
                'name' => 'Finish Trip',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 217,
                'module_id' => 253,
                'name' => 'Print Package List',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 218,
                'module_id' => 253,
                'name' => 'Print Package List All',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 219,
                'module_id' => 253,
                'name' => 'Add Package',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 220,
                'module_id' => 253,
                'name' => 'Set Package Status',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 221,
                'module_id' => 253,
                'name' => 'Take Out',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 222,
                'module_id' => 253,
                'name' => 'Print Package',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            //** Completed */
            [
                'id' => 223,
                'module_id' => 254,
                'name' => 'Edit Package',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            //** Driver Transaction */
            [
                'id' => 224,
                'module_id' => 255,
                'name' => 'Deliveries Tab',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 225,
                'module_id' => 255,
                'name' => 'Payments Tab',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 226,
                'module_id' => 255,
                'name' => 'Settle Statement Tab',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 227,
                'module_id' => 255,
                'name' => 'Create Payment',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 228,
                'module_id' => 255,
                'name' => 'Delete Payment',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 229,
                'module_id' => 255,
                'name' => 'Approve Payment',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 230,
                'module_id' => 255,
                'name' => 'Delete Approve Payment',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 231,
                'module_id' => 255,
                'name' => 'Settle Payment',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 232,
                'module_id' => 255,
                'name' => 'Delete Settle Payment',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            //** Driver Commission */
            [
                'id' => 233,
                'module_id' => 257,
                'name' => 'Confirm Disbursement',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            //** Merchant Transaction */
            [
                'id' => 234,
                'module_id' => 258,
                'name' => 'Deliveries Tab',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 235,
                'module_id' => 258,
                'name' => 'Transaction Tab',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 236,
                'module_id' => 258,
                'name' => 'Create Payment',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 237,
                'module_id' => 258,
                'name' => 'Delete Payment',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
        ]);

    }

    public function rollback()
    {
        // Rollback logic, e.g., delete the seeded data
        Permission::query()->delete();
    }
}
