<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
         Permission::insert([
            //** Booking Center */
            [
                'id' => 200,
                'module_id' => 251,
                'name' => 'Quick Order',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 201,
                'module_id' => 251,
                'name' => 'Assign Driver',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 202,
                'module_id' => 251,
                'name' => 'Arrive',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 203,
                'module_id' => 251,
                'name' => 'Change Status',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 204,
                'module_id' => 251,
                'name' => 'Change Driver',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 205,
                'module_id' => 251,
                'name' => 'Delete Order',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 206,
                'module_id' => 251,
                'name' => 'Add Package',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 207,
                'module_id' => 251,
                'name' => 'Edit Package',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 208,
                'module_id' => 251,
                'name' => 'Delete Package',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 209,
                'module_id' => 251,
                'name' => 'Print Daily Package',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],

            //** packages */
            [
                'id' => 210,
                'module_id' => 252,
                'name' => 'Assign Driver',
                'hidden' => 0,
                'category' => 'assign',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 211,
                'module_id' => 252,
                'name' => 'Return to store',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 212,
                'module_id' => 252,
                'name' => 'Change Merchant',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 213,
                'module_id' => 252,
                'name' => 'Delete Package',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 214,
                'module_id' => 252,
                'name' => 'Print Package',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 215,
                'module_id' => 252,
                'name' => 'Edit Package',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 216,
                'module_id' => 253,
                'name' => 'New Trip',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 217,
                'module_id' => 253,
                'name' => 'Finish Trip',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 218,
                'module_id' => 253,
                'name' => 'Print Package List',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 219,
                'module_id' => 253,
                'name' => 'Print Package List All',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 220,
                'module_id' => 253,
                'name' => 'Add Package',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 221,
                'module_id' => 253,
                'name' => 'Set Package Status',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 222,
                'module_id' => 253,
                'name' => 'Take Out',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 223,
                'module_id' => 253,
                'name' => 'Print Package',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            //** Finished package */
            [
                'id' => 224,
                'module_id' => 254,
                'name' => 'Edit Package',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            //** Driver Transaction */
            [
                'id' => 225,
                'module_id' => 255,
                'name' => 'Deliveries Tab',
                'hidden' => 0,
                'category' => 'view',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 226,
                'module_id' => 255,
                'name' => 'Payments Tab',
                'hidden' => 0,
                'category' => 'view',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 227,
                'module_id' => 255,
                'name' => 'Settle Statement Tab',
                'hidden' => 0,
                'category' => 'view',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 228,
                'module_id' => 255,
                'name' => 'Create Payment',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 229,
                'module_id' => 255,
                'name' => 'Delete Payment',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 230,
                'module_id' => 255,
                'name' => 'Approve Payment',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 231,
                'module_id' => 255,
                'name' => 'Delete Approve Payment',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 232,
                'module_id' => 255,
                'name' => 'Settle Payment',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 233,
                'module_id' => 255,
                'name' => 'Delete Settle Payment',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            //** Driver Commission */
            [
                'id' => 234,
                'module_id' => 257,
                'name' => 'Confirm Disbursement',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 302,
                'module_id' => 257,
                'name' => 'Delete Commissions',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            //** Merchant Transaction */
            [
                'id' => 235,
                'module_id' => 258,
                'name' => 'Deliveries Tab',
                'hidden' => 0,
                'category' => 'view',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 236,
                'module_id' => 258,
                'name' => 'Transaction Tab',
                'hidden' => 0,
                'category' => 'view',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 237,
                'module_id' => 258,
                'name' => 'Create Payment',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 238,
                'module_id' => 258,
                'name' => 'Delete Payment',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],

            //** Driver Management */
            [
                'id' => 239,
                'module_id' => 260,
                'name' => 'Add New Driver',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 240,
                'module_id' => 260,
                'name' => 'Modify Driver',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 241,
                'module_id' => 260,
                'name' => 'Modify Driver Commission',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 242,
                'module_id' => 260,
                'name' => 'Create Driver Mobile Account',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 243,
                'module_id' => 260,
                'name' => 'Change Driver Status',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 244,
                'module_id' => 260,
                'name' => 'Set Password',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 245,
                'module_id' => 260,
                'name' => 'Delete Driver',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            //** Merchant Management */
            [
                'id' => 246,
                'module_id' => 261,
                'name' => 'Add New Merchant',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 247,
                'module_id' => 260,
                'name' => 'Modify Merchant',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 248,
                'module_id' => 260,
                'name' => 'Create Merchant Mobile Account',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 303,
                'module_id' => 260,
                'name' => 'Add New Merchant',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 249,
                'module_id' => 260,
                'name' => 'Change Merchant Status',
                'hidden' => 0,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 250,
                'module_id' => 260,
                'name' => 'Set Password',
                'category' => 'special',
                'hidden' => 0,
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 251,
                'module_id' => 260,
                'name' => 'Delete Merchant',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            //Company Profile
            [
                'id' => 252,
                'module_id' => 277,
                'name' => 'Save Company Profile',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            // ,
            // [
            //     'id' => 253,
            //     'module_id' => 277,
            //     'name' => 'Add Social Media',
            //     'hidden' => 0,
            //     'category' => 'create',
            //     'create_uid' => 1,
            //     'update_uid' => 1,
            //     'company_id' => 1,
            //     'branch_id' => 1,
            // ],
            // [
            //     'id' => 254,
            //     'module_id' => 277,
            //     'name' => 'Modify Social Media',
            //     'hidden' => 0,
            //     'category' => 'modify',
            //     'create_uid' => 1,
            //     'update_uid' => 1,
            //     'company_id' => 1,
            //     'branch_id' => 1,
            // ],
            // [
            //     'id' => 255,
            //     'module_id' => 277,
            //     'name' => 'Delete Social Media',
            //     'hidden' => 0,
            //     'category' => 'delete',
            //     'create_uid' => 1,
            //     'update_uid' => 1,
            //     'company_id' => 1,
            //     'branch_id' => 1,
            // ],
            //** Brand Images */
            [
                'id' => 256,
                'module_id' => 278,
                'name' => 'Add New Media',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 257,
                'module_id' => 278,
                'name' => 'Delete Media',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],

            //** Promotion */
            [
                'id' => 258,
                'module_id' => 279,
                'name' => 'Add New Promotion',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 259,
                'module_id' => 279,
                'name' => 'Modify Promotion',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 260,
                'module_id' => 279,
                'name' => 'Delete Promotion',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],

            //** Social Media */
            [
                'id' => 261,
                'module_id' => 280,
                'name' => 'Add New Media',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 262,
                'module_id' => 280,
                'name' => 'Delete Media',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],

            //** Privacy Statement */
            [
                'id' => 263,
                'module_id' => 281,
                'name' => 'Save',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],

            //** Terms and Conditions */
            [
                'id' => 264,
                'module_id' => 282,
                'name' => 'Save',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],

            //** Exchange Rate */
            [
                'id' => 265,
                'module_id' => 283,
                'name' => 'Add New Exchange Rate',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 266,
                'module_id' => 283,
                'name' => 'Modify Exchange Rate',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 267,
                'module_id' => 283,
                'name' => 'Delete Exchange Rate',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],

            //** Product Categories */
            [
                'id' => 268,
                'module_id' => 284,
                'name' => 'Add New',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 269,
                'module_id' => 284,
                'name' => 'Modify',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 270,
                'module_id' => 284,
                'name' => 'Delete',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],

            //** Remarks */
            [
                'id' => 271,
                'module_id' => 285,
                'name' => 'Add New',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 272,
                'module_id' => 285,
                'name' => 'Modify',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 273,
                'module_id' => 285,
                'name' => 'Delete',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],

            //** Location */
            [
                'id' => 274,
                'module_id' => 286,
                'name' => 'Add Country',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 275,
                'module_id' => 285,
                'name' => 'Modify Country',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 276,
                'module_id' => 285,
                'name' => 'Delete Country',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 277,
                'module_id' => 285,
                'name' => 'View Cities',
                'hidden' => 0,
                'category' => 'view',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 278,
                'module_id' => 285,
                'name' => 'Add City',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 279,
                'module_id' => 285,
                'name' => 'Modify City',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 280,
                'module_id' => 285,
                'name' => 'Delete City',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 281,
                'module_id' => 285,
                'name' => 'View Districts (Khan)',
                'hidden' => 0,
                'category' => 'view',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 282,
                'module_id' => 285,
                'name' => 'Add District',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 283,
                'module_id' => 285,
                'name' => 'Modify District',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 284,
                'module_id' => 285,
                'name' => 'Delete District',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 285,
                'module_id' => 286,
                'name' => 'View Communes (Sangkat)',
                'hidden' => 0,
                'category' => 'view',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 286,
                'module_id' => 286,
                'name' => 'Add Commune',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 287,
                'module_id' => 286,
                'name' => 'Modify Commune',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 288,
                'module_id' => 286,
                'name' => 'Delete Commune',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],

            //** Delivery Zones */
            [
                'id' => 289,
                'module_id' => 287,
                'name' => 'Add New',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 290,
                'module_id' => 287,
                'name' => 'Modify',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 291,
                'module_id' => 287,
                'name' => 'Delete',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],

            //** Delivery Zones */
            [
                'id' => 292,
                'module_id' => 288,
                'name' => 'Add New Price List',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 293,
                'module_id' => 288,
                'name' => 'Modify Price List',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 294,
                'module_id' => 288,
                'name' => 'Delete Price List',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 295,
                'module_id' => 288,
                'name' => 'New Zone',
                'hidden' => 1,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 296,
                'module_id' => 288,
                'name' => 'Assign Zone',
                'hidden' => 1,
                'category' => 'special',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 297,
                'module_id' => 288,
                'name' => 'Delete Zone',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 298,
                'module_id' => 288,
                'name' => 'Modify Price',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],

            //** Bank */
            [
                'id' => 299,
                'module_id' => 289,
                'name' => 'Add New',
                'hidden' => 0,
                'category' => 'create',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 300,
                'module_id' => 289,
                'name' => 'Modify',
                'hidden' => 0,
                'category' => 'modify',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
            [
                'id' => 301,
                'module_id' => 289,
                'name' => 'Delete',
                'hidden' => 0,
                'category' => 'delete',
                'create_uid' => 1,
                'update_uid' => 1,
                'company_id' => 1,
                'branch_id' => 1,
            ],
        ]);

    }

    public function rollback()
    {
        // Rollback logic, e.g., delete the seeded data
        Permission::query()->delete();
    }
}
