name: demo-dmsapi.gtechcambodia.com

on:
  push:
    branches:
      - bs-demo-branches 

jobs:
  build:
    #runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Run update.sh on server
      - name: Run update.sh on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /var/www/demo-dmsapi.gtechcambodia.com && bash update.sh
